#!/bin/sh
# usage:
DATA_MODEL_DIR=$1
SCRIPT_DIR="$(dirname "$(realpath "$0")")"

cd "${DATA_MODEL_DIR}"
echo "running $0"
echo "DATA_MODEL_DIR = ${DATA_MODEL_DIR}"
echo "SCRIPT_DIR = ${SCRIPT_DIR}"

DDL_M="${DATA_MODEL_DIR}/schema/gen/ddl_m.sql" 
DDL_M2="${DATA_MODEL_DIR}/schema/gen/ddl_m2.sql" 
SAMPLE_DATA="${DATA_MODEL_DIR}/sample_data/sample_data.sql" 
sed -e 's/BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/SERIAL PRIMARY KEY/' -e 's/BIGINT NOT NULL REFERENCES/INTEGER NOT NULL REFERENCES/' -e 's/BIGINT/INTEGER/' "$DDL_M" > "$DDL_M2"
datafiller --size=5 "$DDL_M2" > "$SAMPLE_DATA"
#psql -d $PGDATABASE -h $PGHOST -p $PGPORT -U $PGUSER -f "${DATA_MODEL_DIR}/sample_data/init.sql"
